import os
import smtplib
from email.message import EmailMessage


class EmailReportSender:

    def __init__(self):

        self.sender_email = os.getenv("REPORT_EMAIL")
        self.sender_password = os.getenv("REPORT_EMAIL_PASSWORD")

        if not self.sender_email or not self.sender_password:
            raise ValueError(
                "REPORT_EMAIL or REPORT_EMAIL_PASSWORD environment variable is not configured."
            )

    def send_report(self, receiver_email, pdf_path):

        if not os.path.exists(pdf_path):
            raise FileNotFoundError(
                f"PDF report not found: {pdf_path}"
            )

        message = EmailMessage()

        message["Subject"] = "AI Cardiovascular Risk Assessment Report"
        message["From"] = self.sender_email
        message["To"] = receiver_email

        message.set_content(
            """Hello,

Please find attached your AI Cardiovascular Risk Assessment medical report.

This report is generated by the AI Cardiovascular Risk Assessment application.

Regards,
AI Cardiovascular Risk Assessment System
"""
        )

        with open(pdf_path, "rb") as file:

            pdf_data = file.read()

        message.add_attachment(
            pdf_data,
            maintype="application",
            subtype="pdf",
            filename=os.path.basename(pdf_path)
        )

        with smtplib.SMTP_SSL(
            "smtp.gmail.com",
            465,
            timeout=30
        ) as smtp:

            smtp.login(
                self.sender_email,
                self.sender_password
            )

            smtp.send_message(message)