import os
import base64
import resend


class EmailReportSender:

    def __init__(self):

        self.api_key = os.getenv("RESEND_API_KEY")

        if not self.api_key:
            raise ValueError(
                "RESEND_API_KEY environment variable is not configured."
            )

        resend.api_key = self.api_key

    def send_report(self, receiver_email, pdf_path):

        if not os.path.exists(pdf_path):
            raise FileNotFoundError(
                f"PDF report not found: {pdf_path}"
            )

        with open(pdf_path, "rb") as file:
            pdf_data = base64.b64encode(file.read()).decode("utf-8")

        params = {
            "from": "AI Cardiovascular Risk Assessment <onboarding@resend.dev>",
            "to": [receiver_email],
            "subject": "AI Cardiovascular Risk Assessment Report",
            "html": """
                <p>Hello,</p>

                <p>
                Please find attached your AI Cardiovascular Risk Assessment
                medical report.
                </p>

                <p>
                This report was generated by the AI Cardiovascular Risk
                Assessment application.
                </p>

                <p>
                Regards,<br>
                AI Cardiovascular Risk Assessment System
                </p>
            """,
            "attachments": [
                {
                    "filename": os.path.basename(pdf_path),
                    "content": pdf_data
                }
            ]
        }

        response = resend.Emails.send(params)

        print("Resend Email Response:")
        print(response)

        return response